### ISSUE TITLE
elements are mis-sized in <List>'s when they have a type

### ISSUE THREAD

**Issue by modosc** [relayjs/relay-devtools#34]
![image](https://user-images.githubusercontent.com/2231664/50703132-06b7c380-1008-11e9-8928-08aa62b8e306.png)

i toyed with the style settings locally and changing `itemSize` from 40 to 48 fixed this but i'm not sure if any other sizes were multiples of this (otherwise i'd have a pr out).

**Comment by kassens** [comment]
We just merged a new approach to the devtools. Sorry for neglecting this so long.

I'm closing the old issues to have a new start with the restarted codebase.
