### ISSUE TITLE
scrolling in a <List> doesn't work

### ISSUE THREAD

**Issue by modosc** [relayjs/relay-devtools#35]
https://monosnap.com/file/bTarkFejXOYkIjOd3a1YXrXoJmahgi

hard to tell from the video (sorry!) but when the number of items in the store goes off the screen you can't scroll. same thing for store updates.

**Comment by kassens** [comment]
We just merged a new approach to the devtools. Sorry for neglecting this so long.

I'm closing the old issues to have a new start with the restarted codebase.
