### ISSUE TITLE
The devtools tab stays in "Connecting to Relay..." state

### ISSUE THREAD

**Issue by ktosiek** [relayjs/relay-devtools#40]
I've checked out 57a1ea56ed0fbec5717f7e2d62069e8998f7f0a7 and the only thing I can see when looking at https://github.com/relayjs/relay-examples is "Connecting to Relay...". There are no errors in the console.
This happens both on relay 4.0.0 (https://github.com/relayjs/relay-examples/commit/af417909c490766a399e8d4370e772005cadd7d8) and 3.0.0 (https://github.com/relayjs/relay-examples/commit/a47720f2223f60dd8e6df6156abf43cca7728133).

**Comment by tyao1** [comment]
I just tried and it works for me. I think it's not related to that commit, it also happened to me before but I don't know why. Usually opening the page in a new tab, reopen the chrome dev tool or restart chrome solves the problem.

**Comment by bencallaway** [comment]
@ktosiek I first ran into this issue using the Chrome extension. After troubleshooting with the standalone version it appears the bootstrapped backend is expected to run on `localhost:3000`. In my case that was also where I was running my own development server. However, after restarting my server on another port Relay DevTools now successfully connects.

The extension neither reports any errors nor appears to be configurable with respect to its backend location. An error message in the console may be the simplest feature that would avoid this confusing situation.

**Comment by tyao1** [comment]
@ktosiek #46 would probably fix it.

**Comment by ktosiek** [comment]
I'm not sure if it was specifically #46, but something did fix it. And the extension seems to work in FF too, just needs a minor styling fix
