### ISSUE TITLE
localstorage access failure leads to no connection

### ISSUE THREAD

**Issue by leebyron** [relayjs/relay-devtools#6]
localstorage is used to save devtools state between uses. If accessing localstate fails - often because of a permissions or capacity failure - then the devtools does not connect to the client.

This also does not present any kind of error dialog, so it's not always clear to the developer why the tool is broken.

Likely related to #4

**Comment by AndreiCalazans** [comment]
Happening with me.
<img width="719" alt="screen shot 2018-04-07 at 08 47 45" src="https://user-images.githubusercontent.com/20777666/38454596-6f120560-3a40-11e8-8aac-0ecedff74ab8.png">

Here is a repo which is reproducible.
check out into `feat/relay_devtools` 

https://github.com/AndreiCalazans/HN_react_native_relay/blob/feat/relay_devtools/src/App.js#L11

**Comment by avijohnson** [comment]
closed with #13
