### ISSUE TITLE
setIcon, dock undefined

### ISSUE THREAD

**Issue by jakubpycha** [relayjs/relay-devtools#7]
After start devtools crashed. Problem is with setIcon, because dock is undefined.
OS: Windows 10 pro x64 1709
Devtools: 1.4.0
Node: v8.9.4

![relay-devtools](https://user-images.githubusercontent.com/2129754/38672857-b8501fba-3e4f-11e8-95ff-75f4a92b0a23.PNG)

**Comment by kassens** [comment]
Fixed by c2a579fdf3fe48dc75a55a20a5c8b00748753252
