### ISSUE TITLE
Actions: There is action which has run for >3d causing other action workflows to fail

### ISSUE THREAD

**Issue by 0xCMP** [relayjs/relay-devtools#78]
Been playing with Github Actions for our company and checked out ones for this project. They're all failing and seems a CI workflow will not finish.

https://github.com/relayjs/relay-devtools/commit/ab7f1c739cc551a8ac545c095140fa60bbb7b584/checks?check_suite_id=307252882

Not sure of the root cause and didn't investigate further, but I figured it's worth mentioning.

**Comment by kassens** [comment]
@0xCMP thanks for letting us know! This is because the organizational account doesn't have GitHub acctions available yet. If you look at my personal fork, the actions run there: https://github.com/kassens/relay-devtools/actions
