### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by baldarian** [relayjs/relay-devtools#86]
Hey!

I was trying to setup the devtools extension but it seems does not work at all. You can find the screenshot attached below.

<img width="1399" alt="Screen Shot 2020-04-05 at 18 53 18" src="https://user-images.githubusercontent.com/40735399/78501895-13791900-776f-11ea-944d-0a7d9f1c1b47.png">

Furthermore, I found another extension that worked and here's the link of it.
https://chrome.google.com/webstore/detail/relay-devtools/oppikflppfjfdpjimpdadhelffjpciba

**Comment by Hubro** [comment]
Can confirm it's just an empty box in the dev tools, completely useless

**Comment by ro-savage** [comment]
I've been using Relay for 18months, and devtools have always been pretty much useless. They rarely work, need to close and open multiple times and then maybe it works.

Not sure if it's the same for everyone, or if it's just some setups.

Do the devtools actually work properly at for the relay / facebook team?

**Comment by tyao1** [comment]
The new relay devtools no longer support old version or relay-runtime.

@dadapoof is actively working on our new devtools internally, and hopefully we will release a new version to the chrome store in August.
