### ISSUE TITLE
Embedded GraphiQL for querying client schema and using relay directives

### ISSUE THREAD

**Issue by soneymathew** [relayjs/relay-devtools#9]
Is there a plan to add an embedded GraphiQL into the dev tools.
I have the following use cases that can get value out of that.

Provided relay tools can use the environment used by the App that is running

1. I need to be able to include client schema extensions in my query
While extending the server schema with client schema extensions, It will be useful for testing the impact of my client schema extensions with the devtools before wiring up the fragments to my react components. Which means I can specify the extended fields in the query while using relay dev tools.

1. All my fragments may have relay specific directives like @arguments and @argumentdefinitions.
I will be able to copy paste my fragment queries and test the query results without stripping out the relay annotations.

**Comment by avijohnson** [comment]
We currently don't have plans to add this feature because Graphiql is a viable solution and is working for now. Closing this for now.

**Comment by soneymathew** [comment]
@avijohnson This is not a issue raised to reimplement GraphiQL.
on the contrary GraphiQL could be embedded within relay-tools and be made aware of the relay specific directives that are defined by relay only.
examples are 
 - `@connection` 
 - `@arguments
 - `@argumentdefinitions`
 - `@__clientField`

If Relay could intercept the queries that goes thru this embedded client do the things necessary and strip out the relay directives and display stages of progression before it is dispatched to server, folks starting out will be able to learn relay better and adjust queries as needed.

The disconnect between the queries defined in relay components is a friction point in learning to use relay. mainly because what is written in code is not what is send to server.

Please let me know if this makes sense.

**Comment by avijohnson** [comment]
HI @soneymathew, 
Thanks for taking the time to write up this issue and also your patience in receiving a response. 
ASFA my previous answer I didn't mean for it to sound like a definitive no to your use case or issue.  

I believe everything you've said above makes sense especially the following:
> ...folks starting out will be able to learn relay better and adjust queries as needed.

I totally agree that the learning curve is a little steep in Relay and our devtools for Relay should help facilitate the process. 
 
So currently our number one priority for these tools is to get them stable and in a state where debugging and visualizing the store is working consistently, and the contribution/fix process is seamless.

Though currently not on our roadmap, I will bring up the idea of adding an embedded GraphiQL panel at our weekly sync and report back to you.

**Comment by kassens** [comment]
We just merged a new approach to the devtools. Sorry for neglecting this so long.

I'm closing the old issues to have a new start with the restarted codebase.
